### Load in numpy

In [3]:
import numpy as np

### The Basics

In [42]:
# Create a NumPy array
a = np.array([1,2,3], dtype='int16') # set data type to int16
print(a)

[1 2 3]


In [43]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # Create a 2D NumPy array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [44]:
# Get Dimension
a.ndim  # Returns the number of dimensions of the array
b.ndim  # Returns the number of dimensions of the array

2

In [45]:
# Get Shape
a.shape  # Returns the shape of the array (number of elements along each dimension)
b.shape  # Returns the shape of the array (number of elements along each dimension)

(2, 3)

In [46]:
# Get Type
a.dtype  # Returns the data type of the elements in the array

dtype('int16')

In [47]:
# Get Size
a.itemsize  # Returns the size in bytes of each element in the array
b.itemsize # Returns the size in bytes of each element in the array
# a byte size is 2 because we set the data type to int16

8

In [48]:
# Get Total Size
a.size # Returns the total number of elements in the array
a.nbytes # Returns the total number of bytes consumed by the array (a.itemsize * a.size)

6

### Accessing / Changing specific elements, rows, columns, etc

In [49]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # Create a 2D NumPy array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [50]:
# Get a specific element [r, c]
a[1, 5]  # Access the element at row 1, column 6 (zero-indexed)
a[1, -2]  # Access the element at row 1, column 6 from the end

np.int64(13)

In [51]:
# Get a specific row [r, :]
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
# Get a specific column [:, c]
a[:, 2] # Access the entire third column (zero-indexed)

array([ 3, 10])

In [53]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]  # Access elements from row 0, columns 1 to 5 with a step size of 2
a[0, 1:-1:2] # Access elements from row 0, columns 1 to the second last with a step size of 2

array([2, 4, 6])

In [55]:
a[1,5] = 20  # Set the element at row 1, column 6 to 20
print(a)

a[:, 2] = 5 # Set the entire third column to 5
print(a)

a[:, 2] = [1,2] # Set the entire third column to a list of values
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [56]:
# Create a 3D NumPy array
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])  # Shape (2, 2, 2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
# Get specific element (work outside in)
b[0,1,1] # Access the element at first block, second row, second column
b[:,0,:] # Access all blocks, first row, all columns

array([[1, 2],
       [5, 6]])

In [59]:
# replace 
b[:, 1, :] = [[9,9], [8,8]]  # Set the second row of all blocks to [9,9] and [8,8]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [61]:
# All 0s matrix
np.zeros(5)  # Create a 1D array of zeros with 5 elements
np.zeros((2, 3))  # Create a 2D array of zeros with shape (2, 3)
np.zeros((2,3,4))  # Create a 3D array of zeros with shape (2, 3, 4)
np.zeros((2,3,3,2))  # Create a 4D array of zeros with shape (2, 3, 4, 5)

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [62]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')  # Create a 3D array of ones with shape (4, 2, 2) and data type int32

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [64]:
# Any other number 
np.full((2,2), 99, dtype='float32')  # Create a 2D array filled with the number 99

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [67]:
# Any other number (full_like)
np.full_like(a, 4)  # Create an array with the same shape as 'a', filled with the number 4
np.full(a.shape, 4)  # Create an array with the same shape as 'a', filled with the number 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
# Random decimal numbers
np.random.rand(4,2)  # Create a 2D array of shape (4, 2) with random decimal numbers between 0 and 1
# we don't need to pass a tuple, we can pass the shape directly as separate arguments

np.random.random_sample(a.shape)  # Create a 2D array with the same shape as 'a' with random decimal numbers between 0 and 1

array([[0.91907486, 0.34335255, 0.47941638, 0.23570792, 0.41864497,
        0.18283139, 0.15407325],
       [0.63894127, 0.96227031, 0.31292864, 0.65610127, 0.42616834,
        0.68412756, 0.88692378]])

In [86]:
# Random Integer values
np.random.randint(7, size=(3,3))  # Create a 2D array of shape (3, 3) with random integers between 0 and 6
np.random.randint(-4, 8, size=(3,3)) # Create a 2D array of shape (3, 3) with random integers between -4 and 7

array([[ 1,  6, -1],
       [-4,  0,  6],
       [ 3,  3,  0]], dtype=int32)

In [ ]:
# The identity matrix (square matrix with 1s on the diagonal and 0s elsewhere)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)  # Repeat each element of 'arr' 3 times
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9  # Set the center element to 9
# print(z)

output[1:-1, 1:-1] = z # Place 'z' in the center of 'output'
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [100]:
a = np.array([1,2,3])

b = a
b[0] = 100 # Modify 'b' will also modify 'a'
print(a)
print(b)

a = np.array([1,2,3])

b = a.copy()
b[0] = 100 # Modify 'b' will not affect 'a'
print(a)
print(b)

[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


### Mathematics

In [102]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [103]:
a + 2  # Add 2 to each element of 'a'

array([3, 4, 5, 6])

In [105]:
a - 2 # Subtract 2 from each element of 'a'

array([-1,  0,  1,  2])

In [106]:
a * 2 # Multiply each element of 'a' by 2

array([2, 4, 6, 8])

In [107]:
a / 2 # Divide each element of 'a' by 2

array([0.5, 1. , 1.5, 2. ])

In [110]:
a += 2 # Add 2 to each element of 'a' in place
a

array([ 7,  8,  9, 10])

In [111]:
b = np.array([1,0,1,0])
a + b # Element-wise addition of 'a' and 'b'

array([ 8,  8, 10, 10])

In [112]:
a ** 2 # Square each element of 'a'

array([ 49,  64,  81, 100])

In [ ]:
# Take the sin and cos of each element
np.sin(a)  # Compute the sine of each element of 'a'
np.cos(a) # Compute the cosine of each element of 'a'

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

#### Linear Algebra

In [117]:
a = np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)  # Matrix multiplication of 'a' and 'b'

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [118]:
# Find the determinan of a matrix
c = np.identity(3)  # Create a 3x3 identity matrix
np.linalg.det(c) # Compute the determinant of 'c'

np.float64(1.0)

#### Statistics

In [120]:
stats = np.array([[1,2,3],[4,5,6]])  # Create a 2D array
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.min(stats, axis=1)  # Find the minimum value along each row
np.min(stats, axis=0)  # Find the minimum value along each column

array([1, 2, 3])

In [127]:
np.max(stats, axis=0) # Find the maximum value along each column

array([4, 5, 6])

In [130]:
np.sum(stats) # Compute the sum of all elements in 'stats'
np.sum(stats, axis=0) # Compute the sum along each column
np.sum(stats, axis=1) # Compute the sum along each row

array([ 6, 15])

#### Reorganizing arrays

In [135]:
before = np.array([[1,2,3,4],[5,6,7,8]])  # Create a 2D array
print(before)  # Print the shape of 'before'

after = before.reshape((8,1))  # Reshape 'before' to a 2D array with shape (8, 1)
print(after)  # Print the reshaped array

after = before.reshape((2,2,2))  # Reshape 'before' to a 3D array with shape (2, 2, 2)
print(after)  # Print the reshaped array

# Reshaping works as long as the total number of elements remains the same

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [138]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2,v1,v2])  # Stack 'v1' and 'v2' vertically (row-wise)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [140]:
# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))  # Stack 'h1' and 'h2' horizontally (column-wise)

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [149]:
filedata = np.genfromtxt('../data/test/data.txt', delimiter=',') # Load data from a text file with comma as the delimiter
filedata = filedata.astype('int32')  # Convert the data type to int32
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   3,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [150]:
filedata > 50  # Create a boolean mask where elements are greater than 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [159]:
filedata[filedata > 50]  # Access elements greater than 50 using the boolean mask

np.any(filedata > 50, axis=0)  # Check if any element in each column is greater than 50

np.all(filedata > 50, axis=1)  # Check if all elements in each row are greater than 50

((filedata > 50) & (filedata < 100)) # Create a boolean mask where elements are greater than 50 and less than 100
(~(filedata > 50) & (filedata < 100)) # Create a boolean mask where elements are not greater than 50 and less than 100

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [154]:
## You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]  # Access elements at indices 1, 2, and 8

array([2, 3, 9])